name: Build, test, and deploy ASP.NET app to Azure Web App - calculadorajuroscompostos-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild JurosCompostos.sln /p:Configuration=Release /p:TargetFrameworkVersion="v4.7"

      - name: Run NUnit tests
        run: |
          mkdir test-results
          & "packages\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" JurosCompostos.Tests\bin\Release\JurosCompostos.Tests.dll --result=test-results\TestResult.xml
        continue-on-error: false

      - name: Run Selenium E2E tests
        run: |
          & "packages\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" JurosCompostos.SeleniumTests\bin\Release\JurosCompostos.SeleniumTests.dll --result=test-results\SeleniumResult.xml
        continue-on-error: false

      - name: Publish to folder
        run: |
          mkdir published
          msbuild JurosCompostos.Web/JurosCompostos.Web.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishDir=published\

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90149024C4794174BEF4FE95C521739C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3DDB13E776FE4FBF94AB9E41B00A019E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D8F139493BF4EB49F9E8835926D512A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calculadorajuroscompostos-web'
          slot-name: 'Production'
          package: ./ASP-app
