# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - calculadorajuroscompostos-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild JurosCompostos.Web\JurosCompostos.Web.csproj `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=Package `
          /p:PackageAsSingleFile=true `
          /p:SkipInvalidConfigurations=true `
          /p:PackageLocation="JurosCompostos.Web/obj/Release/Package" `
          /p:Configuration=Release

      - name: List build output
        continue-on-error: true
        run: Get-ChildItem -Recurse -Path "JurosCompostos.Web/obj/Release/Package"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: JurosCompostos.Web\obj\Release\Package\PackageTmp\

  test:
    name: unit-tests
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild JurosCompostos.sln /p:Configuration=Release

      - name: Install NUnit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory testrunner

      - name: Run unit tests (NUnit)
        run: |
          mkdir test-results
          & "testrunner\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" `
            "JurosCompostos.Test\bin\Release\JurosCompostos.Test.dll" `
            --result="test-results\UnitTestResult.xml"
            
  deploy:
    runs-on: windows-latest
    needs: test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: deploy-folder
  
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FA39B6AA7C924F2BBD130E63387732A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_57D0F2CB8E1A4BB995AB287934E0F39F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A7907E11F9D46A88FB1A6A4415A495D }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calculadorajuroscompostos-web'
          slot-name: 'Production'
          package: deploy-folder
  
  selenium-tests:
    name: selenium-automated-tests
    runs-on: windows-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild JurosCompostos.sln /p:Configuration=Release
      
      - name: Instalar ChromeDriver compatível
        run: nuget install Selenium.WebDriver.ChromeDriver -Version 135.0.7049.4200 -OutputDirectory testrunner

      - name: Verificar versão do ChromeDriver (opcional)
        run: .\testrunner\Selenium.WebDriver.ChromeDriver.135.0.7049.4200\driver\win32\chromedriver.exe --version

      - name: Run Selenium E2E tests
        run: |
          nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory testrunner
          & "testrunner\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" `
            "JurosCompostos.UI.Test\bin\Release\JurosCompostos.UI.Test.dll" `
            --params="baseUrl=https://calculadorajuroscompostos-web.azurewebsites.net" `
            --labels=All
