name: Build, test and deploy ASP.NET app to Azure Web App - calculadorajuroscompostos-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore JurosCompostos.sln

      - name: Build solution
        run: msbuild JurosCompostos.sln /p:Configuration=Release

      - name: Install NUnit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory testrunner

      - name: Run unit tests (NUnit)
        run: |
          mkdir test-results
          & "testrunner\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" `
            "JurosCompostos.Test\bin\Release\JurosCompostos.Test.dll" `
            --result="test-results\UnitTestResult.xml"

      - name: Build and publish web project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" `
          JurosCompostos.Web\JurosCompostos.Web.csproj `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=FileSystem `
          /p:Configuration=Release `
          /p:Platform=AnyCPU `
          /p:PublishUrl=publish_output `
          /verbosity:detailed


      - name: Verificar conteúdo publicado
        run: |
          Get-ChildItem -Recurse -Path publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: publish_output
  deploy:
    runs-on: windows-2022
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90149024C4794174BEF4FE95C521739C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3DDB13E776FE4FBF94AB9E41B00A019E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D8F139493BF4EB49F9E8835926D512A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calculadorajuroscompostos-web'
          slot-name: 'Production'
          package: ./ASP-app

      - name: Run Selenium E2E tests
        run: |
          nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory testrunner
          mkdir selenium-results
          & "testrunner\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" `
            "JurosCompostos.UI.Test\bin\Release\JurosCompostos.UI.Test.dll" `
            --result="selenium-results\SeleniumTestResult.xml" `
            --params="baseUrl=https://calculadorajuroscompostos-web.azurewebsites.net"
