name: Build, test and deploy ASP.NET app to Azure Web App - calculadorajuroscompostos-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore JurosCompostos.sln

      - name: Build solution
        run: msbuild JurosCompostos.sln /p:Configuration=Release

      - name: Install NUnit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory testrunner

      - name: Run unit tests (NUnit)
        run: |
          mkdir test-results
          & "testrunner\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe" `
            "JurosCompostos.Test\bin\Release\JurosCompostos.Test.dll" `
            --result="test-results\UnitTestResult.xml"

      - name: Publish to folder using PublishProfile
        run: |
          msbuild JurosCompostos.Web\JurosCompostos.Web.csproj `
            /p:Configuration=Release `
            /p:PublishProfile=FileSystemProfile `
            /p:VisualStudioVersion=17.0

      - name: Verificar se pasta publicada foi criada
        run: |
          if (!(Test-Path -Path "published")) {
            Write-Error "Publicação falhou: pasta 'published' não encontrada."
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
